# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='powder',
        ),
        migrations.AddField(
            model_name='coffee',
            name='powder',
            field=models.ManyToManyField(to='main.Powder'),
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='syrup',
        ),
        migrations.AddField(
            model_name='coffee',
            name='syrup',
            field=models.ManyToManyField(to='main.Syrup'),
        ),
    ]
