# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-10 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
